metadata-version = "2015-12-19"
log-level = "debug"
interval = 10
onetime = false

[[ template ]]
source = "/etc/rancher-conf/graylog.conf.tmpl"
dest = "/etc/rancher-conf/graylog.conf"

[[ template ]]
source = "/etc/rancher-conf/log4j2.xml.tmpl"
dest = "/etc/rancher-conf/log4j2.xml"
