graylog:
  tty: true
  stdin_open: true
  image: graylog2/server
  volumes_from:
    - graylog-conf
  environment:
    GRAYLOG_DATA_DIR: /graylog
    GRAYLOG_ELASTICSEARCH_SHARDS: '1'
    GRAYLOG_ELASTICSEARCH_REPLICAS: '0'
    GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    GRAYLOG_PASSWORD_SECRET: secret
    GRAYLOG_REST_ENABLE_CORS: 'true'
    GRAYLOG_REST_ENABLE_GZIP: 'true'
    GRAYLOG_WEB_ENABLE_CORS: 'true'
    GRAYLOG_WEB_ENABLE_GZIP: 'true'
    GRAYLOG_WEB_ENDPOINT_URI: http://gl.rancher/api
  labels:
    lb.haproxy.9000.domains: http://gl.rancher
    lb.haproxy.9000.frontend: 80/http
    io.rancher.sidekicks: graylog-conf,graylog-serve

graylog-conf:
  image: finboxio/rancher-graylog-conf:dev
  tty: true
  pid: host
  privileged: true
  labels:
    io.rancher.container.pull_image: always
  volumes:
    - /etc/rancher-conf
    - /opt/rancher/bin

graylog-serve:
  image: finboxio/serve
  tty: true
  command: /etc/rancher-conf
  labels:
    lb.haproxy.3000.frontend: 80/http
    lb.haproxy.3000.domains: http://gls.rancher
  volumes_from:
    - graylog-conf

mongo:
  image: "mongo:3"
  stdin_open: true
  tty: true

elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
  stdin_open: true
  tty: true
