graylog:
  tty: true
  image: graylog2/server
  entrypoint: /opt/rancher/bin/run.sh
  volumes_from:
    - graylog-conf
  environment:
    GRAYLOG_DATA_DIR: /graylog
    GRAYLOG_ELASTICSEARCH_SHARDS: '1'
    GRAYLOG_ELASTICSEARCH_REPLICAS: '0'
    GRAYLOG_ROOT_PASSWORD_SHA2: f4b13bd73cdcd8e3bafbbe07f1f0785ee324e9c06d52157bc84728ff637a160a
    GRAYLOG_PASSWORD_SECRET: vCamCibQ1aRyZDtHrQiXq57173nMYOX6A52prC43H3h6TnchFQOhzFqH5Vs7LfhWhPfOGjcG26vJOM4kly46rfRDggtnlnCI
    GRAYLOG_REST_ENABLE_CORS: 'true'
    GRAYLOG_REST_ENABLE_GZIP: 'true'
    GRAYLOG_WEB_ENABLE_CORS: 'true'
    GRAYLOG_WEB_ENABLE_GZIP: 'true'
    GRAYLOG_WEB_ENDPOINT_URI: http://gla.rancher
  labels:
    lb.haproxy.9000.domains: http://gl.rancher
    lb.haproxy.9000.frontend: 80/http
    lb.haproxy.12900.domains: http://gla.rancher
    lb.haproxy.12900.frontend: 80/http
    io.rancher.sidekicks: graylog-conf,graylog-serve

graylog-conf:
  image: finboxio/rancher-graylog-conf:dev
  tty: true
  pid: host
  privileged: true
  labels:
    io.rancher.container.pull_image: always
  volumes:
    - /Users/Shared/rancher/graylog/data:/graylog
    - /etc/rancher-conf
    - /opt/rancher/bin

graylog-serve:
  image: finboxio/serve
  tty: true
  command: /etc/rancher-conf
  labels:
    lb.haproxy.3000.frontend: 80/http
    lb.haproxy.3000.domains: http://gls.rancher
  volumes_from:
    - graylog-conf

mongo:
  image: "mongo:3"
  volumes:
    - /Users/Shared/rancher/graylog/data/mongo:/data/db

elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
  volumes:
    - /Users/Shared/rancher/graylog/data/elasticsearch:/usr/share/elasticsearch/data
