graylog:
  scale: 1
  metadata:
    fluentd:
      plugins:
        - gelf
        - https://raw.githubusercontent.com/finboxio/rancher-graylog-conf/master/fluentd/out_gelf.rb
      global:
        - type: gelf
          host: graylog.rancher.rancher.internal
          port: 12201
          full_message_key: log
          short_message_key: log
          flush_interval: 5s

  health_check:
    port: 9000
    interval: 2000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
    reinitializing_timeout: 300000
graylog-conf:
  scale: 1
graylog-serve:
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
mongo:
  scale: 1
elasticsearch:
  scale: 1
  metadata:
    fluentd:
      service: |
        <match **>
          @type stdout
        </match>
