graylog:
  scale: 1
  health_check:
    port: 9000
    interval: 2000
    initializing_timeout: 10000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
    reinitializing_timeout: 10000
graylog-conf:
  scale: 1
graylog-serve:
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
mongo:
  scale: 1
elasticsearch:
  scale: 1
